import type { ParkingSession } from '@/types/model'

export const MOCK_SESSIONS: ParkingSession[] = [
  {
    sessionId: 'S001',
    parkingLotId: 'LOT-01',
    vehicleTypeId: 'VT-01',
    vehicleTypeName: 'Ô tô',
    licensePlate: '51A-12345',
    assignedSlotCode: 'F1-A01',
    actualSlotCode: 'F1-A01',
    entryTime: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    parkedTime: new Date(Date.now() - 85 * 60 * 1000).toISOString(),
    isPaid: false,
    status: 'Parked',
  },
  {
    sessionId: 'S002',
    parkingLotId: 'LOT-01',
    vehicleTypeId: 'VT-02',
    vehicleTypeName: 'Xe máy',
    licensePlate: '59B-67890',
    assignedSlotCode: 'F2-B03',
    entryTime: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    isPaid: false,
    status: 'Admitted',
  },
  {
    sessionId: 'S003',
    parkingLotId: 'LOT-01',
    vehicleTypeId: 'VT-01',
    vehicleTypeName: 'Ô tô',
    licensePlate: '30H-11111',
    assignedSlotCode: 'F1-C07',
    actualSlotCode: 'F1-C07',
    entryTime: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    parkedTime: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
    movedTime: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    isPaid: false,
    status: 'Moved',
  },
  {
    sessionId: 'S004',
    parkingLotId: 'LOT-01',
    vehicleTypeId: 'VT-01',
    vehicleTypeName: 'Ô tô',
    licensePlate: '43A-55555',
    assignedSlotCode: 'F3-D02',
    actualSlotCode: 'F3-D02',
    entryTime: new Date(Date.now() - 200 * 60 * 1000).toISOString(),
    parkedTime: new Date(Date.now() - 195 * 60 * 1000).toISOString(),
    exitTime: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    totalFee: 40000,
    isPaid: true,
    status: 'Completed',
  },
  {
    sessionId: 'S005',
    parkingLotId: 'LOT-01',
    vehicleTypeId: 'VT-02',
    vehicleTypeName: 'Xe máy',
    licensePlate: '79K-22222',
    assignedSlotCode: 'F1-B11',
    entryTime: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    isPaid: false,
    status: 'Abandoned',
  },
  {
    sessionId: 'S006',
    reservationId: 'R-009',
    parkingLotId: 'LOT-01',
    vehicleTypeId: 'VT-01',
    vehicleTypeName: 'Ô tô',
    licensePlate: '51F-99888',
    assignedSlotCode: 'F2-A05',
    actualSlotCode: 'F2-A05',
    entryTime: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    parkedTime: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
    isPaid: false,
    status: 'Parked',
  },
  {
    sessionId: 'S007',
    parkingLotId: 'LOT-01',
    vehicleTypeId: 'VT-02',
    vehicleTypeName: 'Xe máy',
    licensePlate: '29A-33344',
    assignedSlotCode: 'F1-A15',
    entryTime: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    isPaid: false,
    status: 'Admitted',
  },
]
